name: MCInventory
main: org.unixminecraft.mcinventory.bukkit.MCInventory
version: 0.0.2
author: unixminecraft
api-version: 1.15

commands:
  inventory:
    description: Perform the inventory commands.
